### ISSUE TITLE
Compilation fails in Makecode

### ISSUE THREAD

**Issue by microbit-mark** [LaboratoryForPlayfulComputation/pxt-BlockyTalkyBLE#2]
Including the blocky talky extension in MakeCode causes compilation to fail

Open https://makecode.microbit.org/_Du68RXfPxfCx and try to Download

results in 

![Screenshot 2019-07-10 at 13 44 15](https://user-images.githubusercontent.com/31242877/60970054-11397980-a319-11e9-9ce3-bd71add05ae8.png)

**Comment by pelikhan** [comment]
Fixed.
